### PR TITLE
feat: forward invoice functionality

### PR DESCRIPTION
**Pull request by vojtaholik**
screenshots

gif

### CODE REVIEW

**Comment by jbranchaud** [comment]
I just check out this branch to try this out. The invoice show URL when used by someone who isn't authenticated (or who doesn't have an account) is in accessible because we short-circuit the user back to the home page.

Maybe we can special case the Invoice Show page as part of the auth-checking redirect logic?

**Comment by jbranchaud** [comment]
> I just checked out this branch to try this out. The invoice show URL when used by someone who isn't authenticated (or who doesn't have an account) is in accessible because we short-circuit the user back to the home page.
> 
> Maybe we can special case the Invoice Show page as part of the auth-checking redirect logic?

Just looked a little closer at these page components. The Invoice Show page does an ability check and if the user is not allowed to view the invoice, then they are redirected to the Invoices Index page.

https://github.com/skillrecordings/products/blob/main/apps/total-typescript/src/pages/invoices/%5BmerchantChargeId%5D.tsx#L67-L72

And the Invoices Index page does the same thing, ability check and redirect user to home page if they don't have permission.

https://github.com/skillrecordings/products/blob/main/apps/total-typescript/src/pages/invoices/index.tsx#L19-L32

**Comment by vojtaholik** [comment]
@jbranchaud great catch! I made it visible to anyone https://github.com/skillrecordings/products/pull/799/commits/afbe5afb434f5aace5195b93bf499257bb20880c

**Review by jbranchaud — APPROVED** [review]
💯

**Pull request merged**
