### PR TITLE
chore: typos

### PR DESCRIPTION
**Pull request by aaronmcadam**
Thank you all so much for Epic Web 🚀 

As a small thank you, I figured I'd fix a few typos I've found while completing the lessons!

### CODE REVIEW

**Review by joelhooks — APPROVED** [review]
Thanks so much! 🎉

**Comment by aaronmcadam** [comment]
I'll leave this PR open for a little while longer in case I find a few more niggles. Thanks for checking this, @joelhooks ❤️

**Comment by aaronmcadam** [comment]
I found a couple more minor fixes. I won't hold these changes back any further because of your launch tonight. 

Best of luck with the launch, everyone!

**Comment by aaronmcadam** [comment]
@joelhooks I don't think I can merge because of the required Vercel deployment checks, so feel free to merge this when you get a second. Cheers!

**Pull request merged**
